version: "3.8"
services:
    # Application
    app:
        container_name: furniture_app
        build:
            context: ./docker/fpm
            dockerfile: Dockerfile
        working_dir: /var/www
        env_file: .env
        volumes:
            - ./:/var/www
        networks:
            - furniture

    # Web Server
    web:
        container_name: nginx
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        working_dir: /var/www
        restart: always
        volumes:
            - ./:/var/www
        ports:
            - "6161:80"
        networks:
            - furniture

    # Database
    database:
        container_name: app_db
        image: mysql:latest
        volumes:
            - ./docker/volumes/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: furniture_db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3312:3306"
        networks:
            - furniture

networks:
    furniture:
        name: "furniture-network"
